---
title: "Code of Conduct"
---

The organizers of R Dev Day \@ PLUS are dedicated to providing a harassment-free event experience for everyone regardless of age, gender, sexual orientation, disability, physical appearance, race, or religion (or lack thereof).

All participants at R Dev Day \@ PLUS are required to agree to the following code of conduct.

The code of conduct applies to all dev day activities including social events. It extends to event-specific exchanges on social media, for instance posts tagged with the identifier of the dev day (#RDevDayPLUS2024) and replies to such posts.

Organizers will enforce this code throughout and expect cooperation in ensuring a safe environment for all.

## Expected Behaviour

All event participants agree to:

-   Be considerate in language and actions, and respect the boundaries of fellow participants.
-   Refrain from demeaning, discriminatory, or harassing behaviour and language. Please refer to [Unacceptable Behaviour](#unacceptable-behaviour) for more details.
-   Alert a member of the organizing team if you notice someone in distress, or observe violations of this code of conduct, even if they seem inconsequential. Please refer to the section titled [What To Do If You Witness or Are Subject To Unacceptable Behaviour](#what-to-do-if-you-witness-or-are-subject-to-unacceptable-behaviour) for more details.

## Unacceptable Behaviour {#unacceptable-behaviour}

Behaviour that is unacceptable includes, but is not limited to:

-   Stalking
-   Deliberate intimidation
-   Unwanted photography or recording
-   Sustained or willful disruption of talks or other events
-   Use of sexual or discriminatory imagery, comments, or jokes
-   Offensive comments related to age, gender, sexual orientation, disability, race or religion
-   Inappropriate physical contact, which can include grabbing, or massaging or hugging without consent.
-   Unwelcome sexual attention, which can include inappropriate questions of a sexual nature, asking for sexual favours or repeatedly asking for dates or contact information.

If you are asked to stop harassing behaviour you should stop immediately, even if your behaviour was meant to be friendly or a joke, it was clearly not taken that way and for the comfort of all event attendees you should stop.

Attendees who behave in a manner deemed inappropriate are subject to actions listed under [Procedure for Code of Conduct Violations](#procedure-for-code-of-conduct-violations).

## Additional Requirements for Dev Day Material

Presentation slides and documents created for, or during, the dev day should not contain offensive or sexualised material.

## Procedure for Code of Conduct Violations {#procedure-for-code-of-conduct-violations}

The organizing team reserves the right to determine the appropriate response for all code of conduct violations. Potential responses include:

-   a formal warning to stop harassing behaviour
-   cancellation or early termination of presentations or other contributions to the programme
-   expulsion from the dev day
-   removal/rejection of dev day contributions
-   removal of sponsorship acknowledgement, without return of sponsorship contribution

## What To Do If You Witness or Are Subject To Unacceptable Behaviour {#what-to-do-if-you-witness-or-are-subject-to-unacceptable-behaviour}

Alert a member of the [organizing team](/index#Organizing-team) if you notice someone in distress, or observe violations of this code of conduct during the dev day, even if they seem inconsequential.

Report code of conduct violations via the [incident report form](https://rfoundation.limequery.com/478496). Reports will be handled by the organizing team; if the report concerns someone on the team, please contact other members of the team directly.

We will take all reports by R Dev Day \@ PLUS participants seriously. This includes incidents outside our spaces and at any point in time. The organizing team reserve the right to exclude people from the dev day based on their past behaviour, including behaviour outside R Dev Day \@ PLUS spaces and behaviour towards people who are not part of the dev day.

We will respect confidentiality requests for the purpose of protecting targets of harassing behaviour. We will not name victims without their affirmative consent. Correspondence is handled confidentially and deleted after the case is resolved. All data is stored securely, access will be limited to the members of the organizing team who receive the report.

The organizing team will provide support to victims, which may include:

-   providing an escort,

-   contacting the on-campus security or off-campus emergency services,

or otherwise assisting those experiencing harassment to ensure that they feel safe for the duration of the event. Assistance will only be provided with affirmative consent of the victim.

## Acknowledgements

Parts of the above text are licensed [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/). Credit to [SRCCON](https://srccon.org/conduct/). This code of conduct was based on that developed for [useR! 2018](https://user2018.r-project.org/code_of_conduct/) which was a revision of the code of conduct used at previous useR!s and also drew from [rOpenSci's code of conduct](https://ropensci.org/coc/).
